# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e201ebe54b8ef8489c0bfda583e799e042403ccde7ae1ce7243dd076ac8bb1efbef3c706d10e0c54be4bf2fc4a6f51fcbaedf95fb768395ee0a42a97d3659dd2

test:
  secret_key_base: 51ab7a62d29c2cfccc43bf8162b14751ab03e61f723249148753f2eb5e9940a14c58226445994faf222706cfa2d5faac43514eff3aa4cefda248c21ef3aa4eed

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
